'use client';

import { useLanguage } from '@/src/lib/LanguageContext';
import { Shield } from 'lucide-react';

export default function PrivacyPage() {
  const { t, locale } = useLanguage();

  return (
    <div className="p-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <Shield className="w-8 h-8 text-indigo-400" />
            <h1 className="text-4xl font-bold">{t('privacy_title')}</h1>
          </div>
          <p className="text-gray-400 text-lg">
            {t('privacy_content')}
          </p>
        </div>

        {/* Content - English version (Sergio will provide translations) */}
        <div className="bg-gray-900 border border-gray-800 rounded-2xl p-8">
          <div className="prose prose-invert max-w-none">
            <h1>Privacy Policy</h1>
            <p>Last updated: July 12, 2026</p>
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li><p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p></li>
              <li><p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p></li>
              <li><p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to zeusx.</p></li>
              <li><p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p></li>
              <li><p><strong>Country</strong> refers to: Italy</p></li>
              <li><p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p></li>
              <li><p><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</p></li>
              <li><p><strong>Service</strong> refers to the Website.</p></li>
              <li><p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p></li>
              <li><p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
              <li><p><strong>Website</strong> refers to zeusx, accessible from <a href="http://zeusxapps.com" rel="external nofollow noopener" target="_blank" className="text-blue-400 hover:underline">http://zeusxapps.com</a>.</p></li>
              <li><p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p></li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul>
              <li>Email address</li>
              <li>First name and last name</li>
            </ul>

            <h3>Third-Party Infrastructure & Services</h3>
            <p>To deliver our Service securely and process transactions efficiently, we rely on trusted third-party providers. Your data is handled in accordance with their privacy standards and security protocols:</p>
            <ul>
              <li>
                <p><strong>Database & Authentication (Supabase):</strong> We use Supabase to manage user authentication and secure database storage. Your account information (including encrypted credentials and email address) is stored within Supabase's infrastructure. Supabase maintains high security standards in compliance with applicable data protection regulations (including GDPR).</p>
              </li>
              <li>
                <p><strong>Payment Processing & Subscriptions (Lemon Squeezy):</strong> All billing, payments, and subscription management are handled externally by Lemon Squeezy, LLC acting as our Merchant of Record. When purchasing a paid tier, your commercial transaction is governed by Lemon Squeezy's Terms of Service and Privacy Policy. Our Company does not collect, see, or store your credit card details or financial credentials.</p>
              </li>
            </ul>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

            <h4>Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include Session and Persistent Cookies administered by Us to provide essential features, handle user sessions, prevent fraud, and remember your language or login preferences.</p>

            <h3>Use of Your Personal Data</h3>
            <p>The Company may use Personal Data to provide and maintain our Service, manage Your Account, perform service-related contracts, contact You regarding security or product updates, and attend to Your support requests.</p>

            <h3>Retention of Your Personal Data</h3>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. Account information is typically retained for the duration of your account relationship plus up to 24 months after closure to handle any post-termination issues or legal claims. Customer support tickets and website analytics/server logs are kept for up to 24 months for troubleshooting and quality assurance.</p>

            <h3>Transfer of Your Personal Data</h3>
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>

            <h3>Delete Your Personal Data</h3>
            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update or delete Your info at any time by signing in to Your Account settings or contacting us directly.</p>

            <h3>Security of Your Personal Data</h3>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

            <h2>Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16.</p>

            <h2>Changes to this Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
              <li>By email: <span className="font-semibold">support@zeusxapps.com</span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}